#!/bin/sh

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/idk
CONFIG_DIR=/etc/idk
USAGE="usage: $0"

error_exit ()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

user_dir='/var/local/lib/idk/user'
mkdir -p "$user_dir" || error_exit "Cannot create $user_dir"
chmod 1777 "$user_dir"

cd $DEST_DIR/solo
$DEST_DIR/bin/chef-solo -c solo.rb -j dna.json || error_exit 'Failed chef-solo run'

ln -sf $DEST_DIR/bin/idk /usr/bin || error_exit "Cannot link idk to /usr/bin"

exit 0
