#!/bin/sh
#
# Perform necessary idk setup steps
# after package is installed.
#

PROGNAME="`basename "$0"`"

error_exit ()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /var/local/lib/idk/user
chmod 1777 /var/local/lib/idk/user

echo "Thank you for installing idk!"

if [ ! -f /var/local/lib/idk/setup.stamp ] ; then
    echo "To set up IDK, run \`/opt/idk/bin/idk setup\' in your user account."
fi

exit 0
