#!/bin/sh
#
# Perform necessary idk setup steps
# after package is installed.
#

PROGNAME="`basename "$0"`"

error_exit ()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /var/local/lib/idk/user
chmod 1777 /var/local/lib/idk/user

/opt/idk/bin/idk solo

echo "Thank you for installing idk!"

exit 0
