#!/bin/sh

PROGNAME="`basename "$0"`"

error_exit ()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

user_dir='/var/local/lib/idk/user'
mkdir -p "$user_dir" || error_exit "Cannot create $user_dir"
chmod 1777 "$user_dir"

ln -sf /opt/idk/bin/idk /usr/bin/ || error_exit "Cannot link idk to /usr/bin"

echo 'Now run `idk setup` command from your user account to complete installation.'

exit 0
